"""Add box and next_review_date to Card model

Revision ID: cb4c5bda903d
Revises: cc41036a2817
Create Date: 2024-07-17 15:35:50.782042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4c5bda903d'
down_revision = 'cc41036a2817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('box', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('box')

    # ### end Alembic commands ###
